/// Model representing a single GPS location point
class LocationPoint {
  final int? id; // BIGSERIAL in Supabase, autoincrement in SQLite
  final String tripId;
  final double latitude;
  final double longitude;
  final double? accuracy; // in meters
  final double? altitude; // in meters
  final double? speed; // in m/s
  final double? bearing; // degrees from north (0-360)
  final DateTime timestamp;
  final DateTime createdAt;

  // For local sync tracking
  final DateTime? syncedAt;

  LocationPoint({
    this.id,
    required this.tripId,
    required this.latitude,
    required this.longitude,
    this.accuracy,
    this.altitude,
    this.speed,
    this.bearing,
    required this.timestamp,
    DateTime? createdAt,
    this.syncedAt,
  }) : createdAt = createdAt ?? DateTime.now();

  /// Create a copy with some fields replaced
  LocationPoint copyWith({
    int? id,
    String? tripId,
    double? latitude,
    double? longitude,
    double? accuracy,
    double? altitude,
    double? speed,
    double? bearing,
    DateTime? timestamp,
    DateTime? createdAt,
    DateTime? syncedAt,
  }) {
    return LocationPoint(
      id: id ?? this.id,
      tripId: tripId ?? this.tripId,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      accuracy: accuracy ?? this.accuracy,
      altitude: altitude ?? this.altitude,
      speed: speed ?? this.speed,
      bearing: bearing ?? this.bearing,
      timestamp: timestamp ?? this.timestamp,
      createdAt: createdAt ?? this.createdAt,
      syncedAt: syncedAt ?? this.syncedAt,
    );
  }

  /// Convert to JSON for Supabase
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'trip_id': tripId,
      'latitude': latitude,
      'longitude': longitude,
      'accuracy': accuracy,
      'altitude': altitude,
      'speed': speed,
      'bearing': bearing,
      'timestamp': timestamp.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      // Note: geom field is auto-generated by trigger in Supabase
    };
  }

  /// Create from JSON (from Supabase)
  factory LocationPoint.fromJson(Map<String, dynamic> json) {
    return LocationPoint(
      id: json['id'] as int?,
      tripId: json['trip_id'] as String,
      latitude: (json['latitude'] as num).toDouble(),
      longitude: (json['longitude'] as num).toDouble(),
      accuracy: json['accuracy'] != null
          ? (json['accuracy'] as num).toDouble()
          : null,
      altitude: json['altitude'] != null
          ? (json['altitude'] as num).toDouble()
          : null,
      speed:
          json['speed'] != null ? (json['speed'] as num).toDouble() : null,
      bearing: json['bearing'] != null
          ? (json['bearing'] as num).toDouble()
          : null,
      timestamp: DateTime.parse(json['timestamp'] as String),
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  /// Convert to Map for SQLite (local database)
  Map<String, dynamic> toLocalDb() {
    return {
      if (id != null) 'id': id,
      'trip_id': tripId,
      'latitude': latitude,
      'longitude': longitude,
      'accuracy': accuracy,
      'altitude': altitude,
      'speed': speed,
      'bearing': bearing,
      'timestamp': timestamp.millisecondsSinceEpoch,
      'created_at': createdAt.millisecondsSinceEpoch,
      'synced_at': syncedAt?.millisecondsSinceEpoch,
    };
  }

  /// Create from SQLite Map
  factory LocationPoint.fromLocalDb(Map<String, dynamic> map) {
    return LocationPoint(
      id: map['id'] as int?,
      tripId: map['trip_id'] as String,
      latitude: (map['latitude'] as num).toDouble(),
      longitude: (map['longitude'] as num).toDouble(),
      accuracy: map['accuracy'] != null
          ? (map['accuracy'] as num).toDouble()
          : null,
      altitude: map['altitude'] != null
          ? (map['altitude'] as num).toDouble()
          : null,
      speed:
          map['speed'] != null ? (map['speed'] as num).toDouble() : null,
      bearing: map['bearing'] != null
          ? (map['bearing'] as num).toDouble()
          : null,
      timestamp:
          DateTime.fromMillisecondsSinceEpoch(map['timestamp'] as int),
      createdAt:
          DateTime.fromMillisecondsSinceEpoch(map['created_at'] as int),
      syncedAt: map['synced_at'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['synced_at'] as int)
          : null,
    );
  }

  /// Check if location needs sync
  bool get needsSync => syncedAt == null;

  /// Get speed in km/h
  double? get speedKmh => speed != null ? speed! * 3.6 : null;

  /// Check if location is valid (within bounds)
  bool get isValid {
    return latitude >= -90 &&
        latitude <= 90 &&
        longitude >= -180 &&
        longitude <= 180;
  }

  @override
  String toString() {
    return 'LocationPoint(id: $id, lat: $latitude, lon: $longitude, speed: $speed, timestamp: $timestamp)';
  }
}
